### ISSUE TITLE
armProgramの構造

### ISSUE THREAD

**Issue by masudam** [hhiruma/interactive_sensing#2]
もっと綺麗な書き方と言うか，流れがありそう
今のところ，次の楽譜が「４」つまり叩かないならmoveArm()に行かず，そうでないならmoveArm()に現在地と移動すべき場所の差を送ってから現在地を次の場所（つまり移動すべき場所）に書き換えてる
で，moveArm関数では受けとった差分動くようにしてる

って今書いてる時に思い出したんだけど，サーボモータを動かす時に渡す角度って現在地によって変わらず固定（いまいる場所から何度とかではなく０度の角度から何度か）だから，普通に次の場所のナンバーを送ってそれによって動かす角度を変えればいいだけだった
だから，差を送るんじゃなくて普通に次の場所（楽譜）送っていいかも，叩かない処理もそっちでやればいいような気がしてきた

**Comment by hhiruma** [comment]
絶対値を受け取ってそれを直接反映するような仕様に変更した
